name: CI Build
'on':
<<<<<<< HEAD:.github/workflows/ci-build.yml
  workflow_dispatch: 
=======
  workflow_dispatch: true
>>>>>>> master:.github/workflows/ci-build.yml_initial
  pull_request:
    types:
      - closed
    branches:
      - master
  push:
    branches-ignore:
      - '*'
jobs:
  build:
    if: >-
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'CI:Build')
    runs-on:
      - self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build and Push Image
        run: >
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/go-ethereum:${{
          github.sha }}"

          docker build -t $IMAGE_NAME -f ./Dockerfile .

          docker push $IMAGE_NAME echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
      - name: Upload Image Tag
        uses: actions/upload-artifact@v3
        with:
          name: image-tag
          path: |
            ${{ env.IMAGE_NAME }}
<<<<<<< HEAD:.github/workflows/ci-build.yml
      - name: Trigger Devnet Setup
        uses: actions/github-script@v6
        with: 
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'ci-devnet.yml',
            ref: context.ref,
            inputs: {
              image_tag: '${{ env.IMAGE_NAME }}'
            }
          })
=======
      - name: Create Docker Compose File
        run: |
          echo 'version: "3.8"
          services:
            devnet:
              image: ghcr.io/${{ github.repository_owner }}/go-ethereum:${{
          github.sha }}
              ports:
                - "8545:8545"' > ./docker-compose.devnet.yml
      - name: Commit Updated Docker Compose
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./docker-compose.devnet.yml
          git commit -m "Update docker-compose.devnet.yml with new image"
          git push
>>>>>>> master:.github/workflows/ci-build.yml_initial

