name: CI Devnet Setup
'on':
  workflow_dispatch:
    inputs:
      image_tag:
        description: Docker image tag to use
        required: true
        default: 'ghcr.io/elmarino-o/go-ethereum:latest'
jobs:
  setup-devnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Image Tag
        uses: actions/download-artifact@v3
        with:
          name: image-tag
          path: ./artifacts
      - name: Set Image Tag
        run: |
          IMAGE_NAME=$(cat ./artifacts/image-tag)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
      - name: Create Docker Compose File
        run: |
          echo 'version: "3.8"
          services:
            devnet:
              image: ${{ env.IMAGE_NAME }}
              ports:
                - "8545:8545"' > ./docker-compose.devnet.yml
      - name: Commit Updated Docker Compose
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./docker-compose.devnet.yml
          git commit -m "Update docker-compose.devnet.yml with new image"
          git push

